[package]
name = "countdown"
version = "0.1.0"
authors = ["Lee Thomas <leet944@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"

[[bin]]
name = "countdown"
path = "main.rs"
